import io
from fpdf import FPDF
from typing import Dict, Any

class TripItineraryPDF(FPDF):
    def header(self):
        # Draw a header band
        self.set_fill_color(79, 70, 229) # Indigo accent color (#4F46E5)
        self.rect(0, 0, 210, 35, 'F')
        
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 18)
        self.set_y(10)
        self.cell(0, 8, 'AI SMART TRAVEL PLANNER', 0, 1, 'C')
        self.set_font('Helvetica', 'I', 11)
        self.cell(0, 6, 'Your Intelligent Day-by-Day Personalized Travel Guide', 0, 1, 'C')
        self.ln(12)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by AI Travel Planner using NLP & Gemini', 0, 0, 'C')

def clean_txt(val: Any) -> str:
    """
    Cleans and normalizes string inputs to prevent FPDFUnicodeEncodingException.
    Replaces the Unicode Rupee symbol (₹) with 'Rs. ' and sanitizes other unsupported characters.
    """
    if val is None:
        return ""
    
    # Convert to string
    s = str(val)
    
    # Map common unsupported Unicode characters to their Latin-1 equivalents
    s = s.replace("₹", "Rs. ")
    s = s.replace("\u20b9", "Rs. ") # Unicode Rupee sign
    s = s.replace("\u2013", "-").replace("\u2014", "-") # en-dash and em-dash
    s = s.replace("\u201c", '"').replace("\u201d", '"') # double quotes
    s = s.replace("\u2018", "'").replace("\u2019", "'") # single quotes
    s = s.replace("\u2022", "*") # bullet points
    
    # Encode as latin-1, replacing any unmappable characters with a question mark (?)
    try:
        return s.encode('latin-1', 'replace').decode('latin-1')
    except Exception:
        return s

def generate_trip_pdf(itinerary_data: Dict[str, Any], hotels_data: list = None) -> bytes:
    """
    Generates a beautifully formatted PDF document of the trip itinerary.
    Returns the PDF content as bytes.
    """
    pdf = TripItineraryPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Setup text colors
    pdf.set_text_color(33, 37, 41)
    
    # 1. TRIP OVERVIEW
    overview = itinerary_data.get("trip_overview", {})
    dest = overview.get("destination", "Your Destination").upper()
    days = overview.get("days", 3)
    budget = overview.get("budget", 0)
    theme = overview.get("theme", "General Sightseeing")
    
    pdf.set_font('Helvetica', 'B', 16)
    pdf.set_text_color(79, 70, 229)
    pdf.cell(0, 10, f"PERSONALIZED TRIP TO {clean_txt(dest)}", 0, 1, 'L')
    pdf.set_draw_color(79, 70, 229)
    pdf.line(10, 48, 200, 48)
    pdf.ln(5)
    
    # Highlights Table
    pdf.set_text_color(33, 37, 41)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(45, 8, "Duration:", 0, 0)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(45, 8, f"{days} Days", 0, 1)
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(45, 8, "Total Trip Budget:", 0, 0)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(45, 8, f"INR {budget:,.2f}", 0, 1)
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(45, 8, "Trip Theme/Focus:", 0, 0)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(45, 8, clean_txt(theme.capitalize()), 0, 1)
    pdf.ln(5)
    
    # 2. BUDGET BREAKDOWN
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(79, 70, 229)
    pdf.cell(0, 8, "ESTIMATED EXPENSE ALLOCATION", 0, 1, 'L')
    pdf.set_text_color(33, 37, 41)
    
    # Table Header
    pdf.set_fill_color(240, 240, 255)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(110, 8, "Expense Category", 1, 0, 'L', True)
    pdf.cell(80, 8, "Estimated Cost (INR)", 1, 1, 'R', True)
    
    pdf.set_font('Helvetica', '', 10)
    breakdown = itinerary_data.get("budget_breakdown", {})
    categories = [
        ("hotel", "Accommodation / Hotel"),
        ("food", "Food & Dining"),
        ("transportation", "Local & Interstate Transport"),
        ("attractions_activities", "Sightseeing & Activity Fees"),
        ("shopping_misc", "Shopping & Miscellaneous")
    ]
    
    for key, label in categories:
        cost = breakdown.get(key, 0)
        pdf.cell(110, 8, clean_txt(label), 1, 0, 'L')
        pdf.cell(80, 8, f"Rs. {cost:,.2f}", 1, 1, 'R')
        
    pdf.set_font('Helvetica', 'B', 10)
    total_est = breakdown.get("total_estimated_cost", sum(breakdown.get(k, 0) for k, _ in categories))
    pdf.cell(110, 8, "Total Estimated Expenses", 1, 0, 'L', True)
    pdf.cell(80, 8, f"Rs. {total_est:,.2f}", 1, 1, 'R', True)
    pdf.ln(10)
    
    # 3. TRANSIT & LOGISTICS
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(79, 70, 229)
    pdf.cell(0, 8, "TRANSPORT & LOGISTICS SUGGESTIONS", 0, 1, 'L')
    pdf.set_text_color(33, 37, 41)
    pdf.set_font('Helvetica', '', 10)
    
    trans = itinerary_data.get("transport_suggestions", {})
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, "Local Commute:", 0, 1)
    pdf.set_font('Helvetica', '', 10)
    pdf.multi_cell(0, 5, clean_txt(trans.get("local_commute", "Rent a scooter or walk to nearby destinations.")))
    pdf.ln(2)
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, "Reaching the Destination:", 0, 1)
    pdf.set_font('Helvetica', '', 10)
    pdf.multi_cell(0, 5, clean_txt(trans.get("interstate_commute", "Take a flight or rail directly to the main terminal.")))
    
    # 4. HOTEL RECOMMENDATIONS (If provided)
    if hotels_data:
        pdf.add_page()
        pdf.set_font('Helvetica', 'B', 14)
        pdf.set_text_color(79, 70, 229)
        pdf.cell(0, 10, "RECOMMENDED ACCOMMODATIONS", 0, 1, 'L')
        pdf.set_draw_color(79, 70, 229)
        pdf.line(10, 42, 200, 42)
        pdf.ln(5)
        
        for hotel in hotels_data:
            pdf.set_text_color(79, 70, 229)
            pdf.set_font('Helvetica', 'B', 11)
            pdf.cell(130, 6, f"{clean_txt(hotel.get('name', 'Hotel Name'))} ({clean_txt(hotel.get('category', ''))})", 0, 0)
            pdf.set_text_color(245, 158, 11) # Gold color
            pdf.cell(60, 6, f"Rating: {hotel.get('rating', 'N/A')} Stars", 0, 1, 'R')
            
            pdf.set_text_color(33, 37, 41)
            pdf.set_font('Helvetica', 'I', 9)
            pdf.cell(0, 5, f"Est. Price Range: {clean_txt(hotel.get('price_range', 'Contact hotel'))}", 0, 1)
            
            pdf.set_font('Helvetica', '', 9)
            pdf.multi_cell(0, 4, clean_txt(hotel.get('description', '')))
            
            features = ", ".join(hotel.get('features', []))
            if features:
                pdf.set_font('Helvetica', 'B', 8)
                pdf.cell(25, 4, "Key Amenities: ", 0, 0)
                pdf.set_font('Helvetica', '', 8)
                pdf.cell(0, 4, clean_txt(features), 0, 1)
            pdf.ln(5)
            
    # 5. DAY-WISE ITINERARY
    pdf.add_page()
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(79, 70, 229)
    pdf.cell(0, 10, "DETAILED DAY-WISE SCHEDULE", 0, 1, 'L')
    pdf.set_draw_color(79, 70, 229)
    pdf.line(10, 42, 200, 42)
    pdf.ln(5)
    
    itinerary = itinerary_data.get("day_wise_itinerary", [])
    for day in itinerary:
        # Keep Day headings grouped
        pdf.set_font('Helvetica', 'B', 12)
        pdf.set_text_color(79, 70, 229)
        pdf.cell(0, 8, f"DAY {day.get('day', 1)}: {clean_txt(day.get('title', 'Exploration'))}", 0, 1, 'L')
        pdf.set_draw_color(220, 220, 220)
        
        activities = day.get("activities", [])
        for act in activities:
            pdf.set_text_color(33, 37, 41)
            pdf.set_font('Helvetica', 'B', 10)
            
            time_str = act.get('time', 'Morning')
            title_str = act.get('activity', 'Sightseeing')
            cost_str = f"Rs. {act.get('cost', 0):,}" if act.get('cost', 0) > 0 else "Free / Included"
            
            # Print Time & Activity Header
            pdf.cell(25, 6, clean_txt(time_str), 0, 0)
            pdf.cell(125, 6, clean_txt(title_str), 0, 0)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(40, 6, clean_txt(cost_str), 0, 1, 'R')
            
            # Print Details & Location
            pdf.set_text_color(80, 80, 80)
            pdf.set_font('Helvetica', '', 9)
            pdf.cell(25, 5, "", 0, 0)
            
            loc_label = f"Location: {act.get('location', '')}"
            pdf.multi_cell(165, 4.5, clean_txt(act.get('description', '')))
            
            pdf.cell(25, 4, "", 0, 0)
            pdf.set_font('Helvetica', 'I', 8)
            pdf.cell(165, 4, clean_txt(loc_label), 0, 1)
            pdf.ln(2)
            
        # Food Recommendations for the day
        food_recs = day.get("food_recommendations", [])
        if food_recs:
            pdf.ln(2)
            pdf.set_text_color(5, 150, 105) # Green accent
            pdf.set_font('Helvetica', 'B', 9)
            pdf.cell(25, 5, "Local Food Tip:", 0, 0)
            pdf.set_font('Helvetica', '', 9)
            
            food_list = []
            for f in food_recs:
                food_list.append(f"{f.get('name', '')} ({f.get('type', '')} - {f.get('cost_rating', '')})")
            pdf.multi_cell(165, 4.5, clean_txt(", ".join(food_list)))
            
        pdf.ln(6)
        
    # 6. ESSENTIAL TIPS
    pdf.ln(5)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(79, 70, 229)
    pdf.cell(0, 8, "ESSENTIAL TRAVEL TIPS", 0, 1, 'L')
    pdf.set_text_color(33, 37, 41)
    pdf.set_font('Helvetica', '', 10)
    
    tips = itinerary_data.get("essential_tips", [])
    for idx, tip in enumerate(tips):
        pdf.multi_cell(0, 6, clean_txt(f"{idx+1}.  {tip}"))
        pdf.ln(1)
        
    return bytes(pdf.output())

if __name__ == "__main__":
    from itinerary_generator import get_demo_itinerary
    print("Testing PDF Generation...")
    demo = get_demo_itinerary("Shimla", 2, 8000, ["Nature"])
    pdf_bytes = generate_trip_pdf(demo)
    print(f"PDF generated successfully: {len(pdf_bytes)} bytes.")
